services:
  app:
    build: .
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - postgres   # ⬅️ यहाँ db की जगह postgres लिखो

  postgres:       # ⬅️ service का नाम db → postgres कर दिया
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mobifly2024
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
