name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Mobifly2024
          POSTGRES_DB: fastapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1️⃣ Checkout Code
      - uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Cache Dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aiosqlite

      # 5️⃣ Run Tests
      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/fastapi
        run: pytest -v

      # 6️⃣ Build Docker Image
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # 7️⃣ Run Docker Container with network
      - name: Run Docker Container
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:${{ secrets.POSTGRES_PASSWORD }}@host.docker.internal:5432/fastapi
        run: |
          docker run -d -p 8000:8000 --name myapp --env DATABASE_URL=$DATABASE_URL myapp:latest
          sleep 15
          docker ps -a
          docker logs myapp

      # 8️⃣ Healthcheck
      - name: Healthcheck
        run: |
          for i in {1..12}; do
            if curl -s http://localhost:8000/docs; then
              echo "✅ App is up!"
              exit 0
            fi
            echo "⏳ Waiting for app..."
            sleep 5
          done
          echo "❌ App failed to start"
          docker logs myapp
          exit 1
