name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Mobifly2024
          POSTGRES_DB: fastapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1️⃣ Checkout Code
      - uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Cache Dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aiosqlite

      # 5️⃣ Run Tests
      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:Mobifly2024@localhost:5432/fastapi
        run: pytest -v

      # 6️⃣ Run FastAPI app
      - name: Run FastAPI app
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:Mobifly2024@localhost:5432/fastapi
        run: |
          # Run app in background
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10

      # 7️⃣ Healthcheck
      - name: Healthcheck
        run: |
          for i in {1..12}; do
            if curl -s http://localhost:8000/docs; then
              echo "✅ App is up!"
              exit 0
            fi
            echo "⏳ Waiting for app..."
            sleep 5
          done
          echo "❌ App failed to start"
          exit 1
